" Plugins 
source $HOME/.config/nvim/vim-plug/plugins.vim
" Modules 
source $HOME/.config/nvim/modules/base.vim 
source $HOME/.config/nvim/modules/mappings.vim 
source $HOME/.config/nvim/modules/airline.vim 
source $HOME/.config/nvim/modules/vimwiki.vim 
source $HOME/.config/nvim/modules/fzf.vim 
source $HOME/.config/nvim/modules/vim-startify.vim
source $HOME/.config/nvim/modules/undotree.vim
